set(ZD_JSON_OUT_DIR "${CMAKE_SOURCE_DIR}/out")

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${ZD_JSON_OUT_DIR}/bin")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${ZD_JSON_OUT_DIR}/lib")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${ZD_JSON_OUT_DIR}/lib")

# Ensure multi-config generators (Visual Studio, Ninja Multi-Config) put outputs directly in out/bin and out/lib
foreach(OUTPUTCONFIG IN LISTS CMAKE_CONFIGURATION_TYPES)
    string(TOUPPER ${OUTPUTCONFIG} CONFIG)
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_${CONFIG} "${ZD_JSON_OUT_DIR}/bin")
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_${CONFIG} "${ZD_JSON_OUT_DIR}/lib")
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_${CONFIG} "${ZD_JSON_OUT_DIR}/lib")
endforeach()