set(ZD_JSON_OUT_DIR "${CMAKE_SOURCE_DIR}/out")

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${ZD_JSON_OUT_DIR}/bin")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${ZD_JSON_OUT_DIR}/lib")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${ZD_JSON_OUT_DIR}/lib")