configure_file(
    "${CMAKE_SOURCE_DIR}/cmake/templates/vcpkg.json.in"
    "${CMAKE_SOURCE_DIR}/vcpkg.json"
    @ONLY
)
configure_file(
    "${CMAKE_SOURCE_DIR}/cmake/templates/version.hpp.in"
    "${CMAKE_SOURCE_DIR}/include/zd_json/version.hpp"
    @ONLY
)