name: CI

on:
  push:
    branches:
      - main
    paths:
      - "include/**"
      - "src/**"
      - "tests/**"
      - "benchmarks/**"
      - "cmake/**"
      - "CMakeLists.txt"
      - "CMakePresets.json"
      - ".github/workflows/**"

  pull_request:
    branches:
      - main
      - feature/**
      - fix/**
      - refactor/**
    paths:
      - "include/**"
      - "src/**"
      - "tests/**"
      - "benchmarks/**"
      - "cmake/**"
      - "CMakeLists.txt"
      - "CMakePresets.json"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Setup LLVM
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: 20

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Configure
        run: |
          cmake -B build \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --parallel

      - name: Test
        run: ctest --test-dir build --output-on-failure