name: Format

on:
  pull_request:

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install clang-format -y

      - name: Check formatting
        run: |
          find include src tests benchmarks \
            \( -name "*.cpp" -o -name "*.hpp" \) \
            | xargs clang-format --dry-run --Werror